- id: "/"
  title: "LOT16 - Lights Of Tuscany 2016"
  description: "Programme for international physics students in the VIRGO, LENS, INFN labs and Universities of Pisa and Florence"
  img: img/logo.png
  keywords: "aisf associazione italiana studenti di fisica iaps lot lights of tuscany pisa firenze"
